language: ruby
rvm:
  - 2.5.1
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/email.yml.example config/email.yml
  - psql -c 'create database go_where_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
